In [1]:
! pip install tensorflow

## **Installing Tensorflow**

In [2]:
import tensorflow as tf

## **Version**

In [3]:
print("tensorflow version", tf.__version__)

tensorflow version 2.15.0


In [4]:
mnist = tf.keras.datasets.mnist

In [5]:
(x_train , y_train) , (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [6]:
x_train , x_test = x_train/255.0 ,x_test/255.0

## **Sequential**

Bun: The base of our burger. It's like the input, where everything starts.
Flatten: We take the bun and make it flat, like squishing it down.
Patty: This is where the magic happens. The dense layer. It's like adding the meat to our burger.
Cheese: Sometimes we add cheese! Dropout layer, where we randomly drop some ingredients to keep things interesting.
Bun: We put the top bun on, finishing our burger. This is our output, the final result.
So, in this simple burger model, we start with the bun (input), flatten it, add the patty (dense layer), maybe add some cheese (dropout), and then put the top bun on (output). And there you have it, a tasty model burger!

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
model

In [14]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.38790396, -0.01310033, -0.59182096, -0.19808465, -0.3993799 ,
         0.50716203,  0.33221287, -0.6218522 ,  0.53495026,  0.07369804]],
      dtype=float32)

In [15]:
tf.nn.softmax(predictions).numpy()

array([[0.13545965, 0.09071018, 0.0508535 , 0.0753908 , 0.06164487,
        0.15261707, 0.12812197, 0.04934901, 0.1569175 , 0.09893548]],
      dtype=float32)

**Loss Function:**
The loss function measures how wrong the model's guesses are compared to the actual answers during training. SparseCategoricalCrossentropy is a specific type of loss function used for training when dealing with classification problems where the classes are mutually exclusive (each example belongs to only one class). It compares the model's output probabilities with the true labels and calculates the error. This helps the model adjust its parameters to improve its predictions during training.

In [16]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Imagine you're playing a guessing game with your friend. You have to guess which animal your friend is thinking of, but you're not very good at guessing yet. You make random guesses, like saying "cat" or "dog" without really knowing.

Now, let's say your friend is thinking of one of ten animals. Since you're just guessing randomly, you have an equal chance of guessing any of those animals, like picking a number from 1 to 10. So, if you're asked to guess, your chance of getting it right is 1 out of 10.

Now, let's talk about how wrong your guess is. Imagine you're keeping track of how far off your guesses are from the right answer. The more off you are, the higher the number gets. In our game, we use a special way to measure this "wrongness." It's like putting a number on how wrong each guess is.

When we start playing, since you're just guessing randomly, your guess could be very off. In fact, there's a special number we use to say how off your guess is. It's about 2.3, but let's just call it "a bit wrong" for now. This special number helps us see how far off your guesses are from the right answer.

So, in simple words, the game is about guessing, and we have a special way to see how wrong each guess is. When you're just starting and guessing randomly, your guesses are "a bit wrong," and we use a special number to show that.

In [17]:
loss_fn(y_train[:1], predictions).numpy()

1.8798232

## **Training**
This code sets up the model for training. We use the Adam optimizer, which is a popular optimization algorithm for training deep learning models. We also specify the loss function loss_fn that we defined earlier, and set the metric to be evaluated during training as accuracy, which tells us how often the model's predictions match the true labels.

In [19]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## **Train and evaluate your model**

Use the Model.fit method to adjust your model parameters and minimize the loss:



In [20]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.2990 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1383 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1048 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0856 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0744 - accuracy: 0.9766


## What are epochs
epochs in training mean how many times the model goes through the entire dataset during training. So, if you set epochs to 5, it means the model will see the entire training data five times, each time trying to learn and improve its predictions.

 ## **Evaluation**
 The Model.evaluate method checks the model's performance, usually on a validation set or test set.



In [21]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0707 - accuracy: 0.9783 - 1s/epoch - 4ms/step


[0.07066787779331207, 0.9782999753952026]

The image classifier is now trained to ~98% accuracy on this dataset.

### **Returning Prob:**
If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:


In [22]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [23]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.0393444e-07, 9.0158707e-09, 1.8055798e-05, 1.1781621e-04,
        1.9876277e-12, 5.5158660e-07, 2.8611835e-13, 9.9985993e-01,
        1.0185155e-07, 2.8812869e-06],
       [2.1953563e-09, 2.7801961e-04, 9.9971634e-01, 5.2307851e-06,
        8.5914727e-16, 2.9168410e-07, 1.9574367e-10, 5.3988574e-13,
        1.0390968e-07, 3.2125442e-15],
       [1.1945870e-07, 9.9915075e-01, 7.3851777e-05, 4.8658990e-06,
        4.7463978e-05, 2.7515832e-06, 2.9687058e-06, 6.1404880e-04,
        9.2289636e-05, 1.1028418e-05],
       [9.9994874e-01, 4.5081050e-11, 3.3769855e-05, 4.9607490e-08,
        7.2050007e-08, 1.3522551e-05, 2.7407411e-06, 3.0853076e-07,
        2.6009579e-07, 6.3265657e-07],
       [9.0607841e-07, 6.4230266e-10, 1.2231896e-05, 2.8603440e-08,
        9.9902081e-01, 1.2435053e-06, 4.0273940e-06, 4.6291734e-05,
        2.0895325e-07, 9.1412727e-04]], dtype=float32)>

# **Conclusion**

Congratulations! You have trained a machine learning model using a prebuilt dataset using the Keras API.